
name : prebuild

on :
  push :
    branches : [ master ]

jobs :

  prebuild :
    if : "startsWith( github.event.head_commit.message, 'version' )"
    runs-on : ${{ matrix.os }}
    strategy :
      fail-fast : false
      matrix :
        os : [ ubuntu-latest, windows-latest, macos-latest ]
        node-version : [ 10.x, 11.x, 12.x, 13.x, 14.x, 15.x ]
    steps :
    - run : git config --global core.autocrlf input
    - run : git config --global user.email "testing@testing.com"
    - run : git config --global user.name "Testing"
    - uses : actions/checkout@v2
    - name : ${{ matrix.node-version }}
      uses : actions/setup-node@v1
      with :
        node-version : ${{ matrix.node-version }}
    - run : npm i --ignore-scripts
    - if : "startsWith( matrix.os, 'windows' ) && startsWith( matrix.node-version, '11' )"
      run : npm config set msbuild_path npm config set msvs_version 2017
    - if : "startsWith( matrix.os, 'windows' ) && startsWith( matrix.node-version, '11' )"
      run : npm config set msbuild_path "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\MSBuild.exe"
    - run : npm run node-pre-gyp-build
    - run : npm run node-pre-gyp-package && npm run node-pre-gyp-github-release
      env :
        NODE_PRE_GYP_GITHUB_TOKEN : ${{ secrets.NODE_PRE_GYP_GITHUB_TOKEN }}
