
name : push

on :
  push :
    branches : [ master ]

jobs :

  Cancel:
    if : "!startsWith( github.event.head_commit.message, 'version' )"
    name : 'Cancel Previous Runs'
    runs-on : ubuntu-latest
    timeout-minutes : 1
    steps :
      - uses : styfle/cancel-workflow-action@0.4.0
        with :
          access_token : ${{ github.token }}
          # workflow_id : ${{ github.workflow }}

  Fast :
    if : "!startsWith( github.event.head_commit.message, 'version' )"
    runs-on : ${{ matrix.os }}
    strategy :
      fail-fast : false
      matrix :
        os : [ ubuntu-latest, windows-latest, macos-latest ]
        node-version : [ 14.x ]
    steps :
    - name : Setup git
      run : |
        git config --global core.autocrlf input
        git config --global user.email "testing@testing.com"
        git config --global user.name "Testing"
        git config --global pull.rebase false
        git config --global init.defaultBranch master
    - uses : actions/checkout@v2
    - name : ${{ matrix.node-version }}
      uses : Wandalen/wretry.action@v1.0.11
      with :
        action : actions/setup-node@v1
        with : |
          node-version : ${{ matrix.node-version }}
        attempt_limit : 3
        attempt_delay: 1000
    - run : npm i --ignore-scripts
    # - run : npm run node-pre-gyp-build
    - name : Build binary module
      uses : Wandalen/wretry.action@v1.0.11
      with :
        command : npm run node-pre-gyp-build
        attempt_limit : 3
        attempt_delay: 1000
    - run : npm test
