
name : GypPublish
on : [ push ]

jobs :

  Full :
    env :
      PRIVATE_WTOOLS_BOT_TOKEN : ${{ secrets.PRIVATE_WTOOLS_BOT_TOKEN }}
      PRIVATE_WTOOLS_BOT_SSH_KEY : ${{ secrets.PRIVATE_WTOOLS_BOT_SSH_KEY }}
      PRIVATE_WTOOLS_BOT_NPM_PASS : ${{ secrets.PRIVATE_WTOOLS_BOT_NPM_PASS }}
      PRIVATE_WTOOLS_BOT_EMAIL : ${{ secrets.PRIVATE_WTOOLS_BOT_EMAIL }}
      NODE_PRE_GYP_GITHUB_TOKEN : ${{ secrets.NODE_PRE_GYP_GITHUB_TOKEN }}
    strategy :
      fail-fast : false
      matrix :
        os : [ ubuntu-latest, windows-latest, macos-latest ]
        node-version : [ 18.x, 20.x ]
    if : "startsWith( github.event.head_commit.message, 'version' ) && startsWith( github.ref, 'refs/tags/v' )"
    runs-on : ${{ matrix.os }}
    steps :
    - name : Setup git
      run : |
        git config --global core.autocrlf input
        git config --global user.email "testing@testing.com"
        git config --global user.name "Testing"
        git config --global pull.rebase false
        git config --global init.defaultBranch master
    - uses : actions/checkout@v4
    - name : ${{ matrix.node-version }}
      uses : Wandalen/wretry.action/post@master
      with :
        action : actions/setup-node@v4
        with : |
          node-version : ${{ matrix.node-version }}
        attempt_limit : 3
        attempt_delay: 1000
    - name : Update node-gyp
      if: ${{ matrix.os == 'windows-latest' }}
      run : |
        npm install --global node-gyp@10.1.0
        npm prefix -g | % {npm config set node_gyp "$_\node_modules\node-gyp\bin\node-gyp.js"}
    - name : Install willbe
      uses : Wandalen/wretry.action/main@master
      with :
        command : npm i -g willbe@latest
        attempt_limit : 3
        attempt_delay: 1000
    - run : npm run clean
    - name : Install submodules
      uses : Wandalen/wretry.action/main@master
      with :
        command : will .npm.install
        attempt_limit : 3
        attempt_delay: 1000
    - run : npm list
      continue-on-error : true
    - name : Build binary module
      uses : Wandalen/wretry.action/main@master
      with :
        command : npm run node-pre-gyp-build
        attempt_limit : 3
        attempt_delay: 1000
    - run : npm test
