
name : publish

on :
  push :
    branches : [ master ]

jobs :

  Full :
    if : "startsWith( github.event.head_commit.message, 'version' )"
    runs-on : ${{ matrix.os }}
    strategy :
      fail-fast : false
      matrix :
        os : [ ubuntu-latest, windows-latest, macos-latest ]
        node-version : [ 10.x, 12.x, 13.x, 14.x, 15.x ]
    steps :
    - name : Setup git
      run : |
        git config --global core.autocrlf input
        git config --global user.email "testing@testing.com"
        git config --global user.name "Testing"
        git config --global pull.rebase false
        git config --global init.defaultBranch master
    - uses : actions/checkout@v2
    - name : ${{ matrix.node-version }}
      uses : Wandalen/wretry.action@v1.0.11
      with :
        action : actions/setup-node@v1
        with : |
          node-version : ${{ matrix.node-version }}
        attempt_limit : 3
        attempt_delay: 1000
    - run : npm i --ignore-scripts
    # - run : npm run node-pre-gyp-build
    - name : Build binary module
      uses : Wandalen/wretry.action@v1.0.11
      with :
        command : npm run node-pre-gyp-build
        attempt_limit : 3
        attempt_delay: 1000
    - run : npm test
